apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage
spec:
# the number of pods to be running for the deployment
  replicas: 2
  selector:
    matchLabels:
      app: webpage
  template:
    metadata:
      labels:
        app: webpage
    spec:
      containers:
      - name: webpage
      # this is the name of the image you pushed to docker hub
        image: clementkoomson/web_site:v1  
        ports:
        - containerPort: 8080
          hostPort: 80